#!/usr/bin/env python3
import skilstak.colors as c
import time as t

try:
    while True:
        print(c.random() + "Hello" + c.random() + " Master")
        t.sleep(1)
        print(c.clear)
except KeyboardInterrupt:
    exit()
